### PR TITLE
Fixes PCA (issue #13) and adds necessary tests

### LINKED ISSUE #13: Inconsistency in PCA scaling
Even though `pcaeig()` and `pca()` take both `center` and `scale` arguments, `pcaeig()` ignores the value of `scale`

<b>EDIT</b>: I see that `C = scale ? cor(X) : cov(X)` is supposed to take care of the scaling in `pcaeig()`, though I got different results when I tried it before. I will investigate more on this.

Also, do others agree that eigenvalues should be scaled back to the original space?

I can take care of this in the next few days or next week, but I would like to know if the latter makes sense to others (we can also add an option for this).

### PR DESCRIPTION
**Pull request by cbecker**
This pull request fixes https://github.com/JuliaStats/DimensionalityReduction.jl/issues/13, also adds necessary tests.

Principal components are now re-scaled to the original space, if scale=true.

### CODE REVIEW

File: src/pca.jl [hunk 1]
```diff
@@ -1,38 +1,65 @@
 
 # Subtracts each column's mean (if center=true),
 # divides by each column's standard deviation (if scale=true).
+# Returns (scaledData, mean, std), where mean or std may be 'nothing'
 function normalize(X::Matrix ; center=true, scale=true)
     n = size(X,1)
+
+    m = nothing
```
Comment (johnmyleswhite) [inline src/pca.jl]: What about using empty vectors instead of `nothing`? I'm concerned about type-instability.

**Comment by johnmyleswhite** [comment]
Other than the comment about `nothing`, this all looks good. Thanks for doing this!

File: src/pca.jl (hunk 1 above)
Comment (cbecker) [inline src/pca.jl]: That's fine for me, but can you exemplify why it would be better to have an empty vector instead of `nothing`? I am still making my way through Julia.

Comment (simonster) [inline src/pca.jl]: Julia compiles functions dynamically for each set of input types encountered. To call the right functions, Julia needs to know what types those functions are operating on. If the return type of a function is consistent, then for any input, Julia knows the type of the output, so when that output is used later, Julia can figure out the right function to call at compile time. If the return type of a function isn't consistent, then to use the output, Julia needs to look up the function to call at runtime. That's not actually a big deal inside `pcasvd`, since it doesn't do much with `Xmean` and `Xstd`, but the inconsistency propagates: if the return type here isn't consistent, then neither is the return type of `pcasvd`, and this goes on to affect the code that called `pcasvd`.

What I really wanted to say here is that these should be empty matrices, since `mean(X, 1)` of a matrix returns a row matrix.

Comment (cbecker) [inline src/pca.jl]: Thanks for the detailed explanation, it is very clear.

So the best would be to return an empty vector of the same type, I guess that `[]` is not good enough, since `typeof([]) -> Array{None,1}`. Therefore the best is to return `eltype(X)[]`, right?

Comment (johnmyleswhite) [inline src/pca.jl]: Yeah, that's the intuition.

Try doing this:

```
function normalize{T}(X::Matrix{T}; center=true, scale=true)
m = T[]
```

Comment (simonster) [inline src/pca.jl]: Per the last line of my comment above, these should be `similar(X, 0, 0)`

Comment (cbecker) [inline src/pca.jl]: I was just thinking about that, because the 'normal' output is a matrix, so `similar(X, 0, 0)` does the job.

**Comment by cbecker** [comment]
Type instability should be fixed now.

File: src/pca.jl [hunk 2]
```diff
@@ -1,38 +1,69 @@
 
 # Subtracts each column's mean (if center=true),
 # divides by each column's standard deviation (if scale=true).
-function normalize(X::Matrix ; center=true, scale=true)
+# Returns (scaledData, mean, std), where mean or std may be 'nothing'
+function normalize{T}(X::Matrix{T} ; center=true, scale=true)
     n = size(X,1)
+
+    local m
```
Comment (cbecker) [inline src/pca.jl:9]: btw, are there any performance issues when using `local var` without initializing it at the same line?
Otherwise it should be ready for merging.

Comment (simonster) [inline src/pca.jl:9]: There are no performance issues, but it shouldn't be necessary. `if` blocks do not introduce a new scope.

Comment (cbecker) [inline src/pca.jl:9]: for some reason I thought `if` did introduce a new scope, it sounds to me that it is more error-prone if it does not (eg. keeping temporary variables around that generally I would want to have deleted). Though this is probably a topic for another discussion.

**Comment by cbecker** [comment]
Forgot to fix the comments of normalize(), done now.

**Comment by cbecker** [comment]
Do you know when this is likely to be reviewed to be merged upstream? Or is there someone else I should contact particularly? Thanks.

**Comment by johnmyleswhite** [comment]
Pinging us is the best way to get things merged. The combination of my schedule and GitHub's infrastructure only sending me e-mails probabilistically means that a couple of pings are usually required.

File: src/pca.jl [hunk 3]
```diff
@@ -1,38 +1,70 @@
 
 # Subtracts each column's mean (if center=true),
 # divides by each column's standard deviation (if scale=true).
-function normalize(X::Matrix ; center=true, scale=true)
+# Returns (scaledData, mean, std), where mean or std may be 
+#  empty matrices if center or scale are false
+function normalize{T}(X::Matrix{T} ; center=true, scale=true)
     n = size(X,1)
+
+    local m
```
Comment (johnmyleswhite) [inline src/pca.jl:9]: I think this `local` isn't actually required, but it's fine for now.

**Comment by cbecker** [comment]
Thanks @johnmyleswhite ! My concern was that this is an important change, because the previous version was buggy, especially with `pcaeig`, so merging it means newcomers can add this package and use PCA without worrying about that. Also the fact that it scales back to the original space, I think is very useful.

I am wondering if we should tag a new release as well, because right now Pkg.update() is not picking the changes up.

**Comment by johnmyleswhite** [comment]
Yes, we should tag a new release. We should also do a big update of the docs to make clear which functions actually work reliably.

**Comment by cbecker** [comment]
So far PCA works fine with my setup, both versions, so I can add more info in README.md.

However, no idea about ICA, NMF and t-SNE. Who shall we ping to query about their status?
